version: '3.8'

services:
  database:
    image: postgres:15-alpine
    container_name: hilfe_db
    ports:
      - "5177:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hilfevonnebenan
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
